{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fmodern Courier New;}}
{\colortbl\red51\green153\blue255;\red0\green0\blue0;\red255\green255\blue255;\red255\green255\blue255;\red128\green0\blue128;}
{\info{\comment Generated by the SynEdit RTF exporter}
{\title Untitled}}

\deflang1033\pard\plain\f0\fs20 \cf0\i //PROCESSO SELETIVO CAPITULO RAS - IEEE UFCG
\par //CANDIDATA: MERCIA REGINA DA SILVA
\par 
\par //MISSAO 1.0: PRIMEIRO CIRCUITO ELETRONICO 
\par //ASCEe os pinos 13, 12 e 11 como OUTPUT como a variavel de saIda
\par 
\par \i0\cf1\b int\b0\cb2  \cb3 vermelho\cb2  \cb3 =\cb2  \cb3\cf4 13\cf1 ;
\par \b int\b0\cb2  \cb3 amarelo\cb2  \cb3 =\cf4 12\cf1 ;
\par \b int\b0\cb2  \cb3 verde\cb2  \cb3 =\cb2  \cb3\cf4 11\cf1 ;
\par 
\par \cf0\i //
\par \i0\cf1\b void\b0\cb2  \cb3 setup()\{
\par \cb2   \cb3 pinMode(vermelho,\cb2  \cb3 OUTPUT);
\par \cb2   \cb3 pinMode(amarelo,\cb2  \cb3 OUTPUT);
\par \cb2   \cb3 pinMode(verde,\cb2  \cb3 OUTPUT);
\par \cb2   
\par \cb3 \}
\par 
\par \cf0\i //Sequencia dos comandos: LOW: BAIXO (ACENDE) ou HIGH: ALTO (APAGA)
\par \i0\cf1\b void\b0\cb2  \cb3 loop()\{
\par \cb2   
\par   \cb3 digitalWrite(vermelho,\cb2  \cb3 LOW);
\par \cb2   \cb3 digitalWrite(amarelo,\cb2  \cb3 HIGH);
\par \cb2   \cb3 digitalWrite(verde,\cb2  \cb3 LOW);
\par \cb2   
\par   \cb3 delay(\cf4 4000\cf1 );\cb2  \cb3\cf0\i //Tempo de espera 4 Segundos (4 s). 
\par 
\par \i0\cb2\cf1   \cb3 digitalWrite(amarelo,\cb2  \cb3 LOW);
\par \cb2   \cb3 digitalWrite(vermelho,\cb2  \cb3 HIGH);
\par 
\par \cb2   \cb3 delay(\cf4 4000\cf1 );\cb2  \cb3\cf0\i //Tempo de espera 4 Segundos (4 s). 
\par \i0\cb2\cf1   
\par   \cb3 digitalWrite(verde,\cb2  \cb3 HIGH);
\par \cb2   \cb3 digitalWrite(vermelho,\cb2  \cb3 LOW);
\par \cb2   
\par   \cb3 delay(\cf4 5000\cf1 );\cb2  \cb3\cf0\i //Tempo de espera 2 Segundos (4 s). 
\par \i0\cb2\cf1   
\par \cb3 \}
\par 
\par 
\par \cb2  
\par   
\par }